spring.application.name=country-finder-mcp
spring.main.banner-mode=off
spring.main.log-startup-info=false
logging.pattern.console=
logging.level.root=OFF

spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=country-finder
spring.ai.mcp.server.version=1.0.0